//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright (c) 2021 by the OnMetal authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	onmetal "github.com/onmetal/gardener-extension-provider-onmetal/pkg/apis/onmetal"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CloudControllerManagerConfig)(nil), (*onmetal.CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudControllerManagerConfig_To_onmetal_CloudControllerManagerConfig(a.(*CloudControllerManagerConfig), b.(*onmetal.CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.CloudControllerManagerConfig)(nil), (*CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(a.(*onmetal.CloudControllerManagerConfig), b.(*CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*onmetal.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_onmetal_CloudProfileConfig(a.(*CloudProfileConfig), b.(*onmetal.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*onmetal.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*onmetal.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_onmetal_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*onmetal.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*onmetal.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*onmetal.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_onmetal_InfrastructureConfig(a.(*InfrastructureConfig), b.(*onmetal.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*onmetal.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*onmetal.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_onmetal_InfrastructureStatus(a.(*InfrastructureStatus), b.(*onmetal.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*onmetal.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*onmetal.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_onmetal_MachineImage(a.(*MachineImage), b.(*onmetal.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_MachineImage_To_v1alpha1_MachineImage(a.(*onmetal.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*onmetal.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_onmetal_MachineImageVersion(a.(*MachineImageVersion), b.(*onmetal.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*onmetal.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*onmetal.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_onmetal_MachineImages(a.(*MachineImages), b.(*onmetal.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_MachineImages_To_v1alpha1_MachineImages(a.(*onmetal.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegionConfig)(nil), (*onmetal.RegionConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegionConfig_To_onmetal_RegionConfig(a.(*RegionConfig), b.(*onmetal.RegionConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.RegionConfig)(nil), (*RegionConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_RegionConfig_To_v1alpha1_RegionConfig(a.(*onmetal.RegionConfig), b.(*RegionConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StorageClass)(nil), (*onmetal.StorageClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StorageClass_To_onmetal_StorageClass(a.(*StorageClass), b.(*onmetal.StorageClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.StorageClass)(nil), (*StorageClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_StorageClass_To_v1alpha1_StorageClass(a.(*onmetal.StorageClass), b.(*StorageClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StorageClasses)(nil), (*onmetal.StorageClasses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StorageClasses_To_onmetal_StorageClasses(a.(*StorageClasses), b.(*onmetal.StorageClasses), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.StorageClasses)(nil), (*StorageClasses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_StorageClasses_To_v1alpha1_StorageClasses(a.(*onmetal.StorageClasses), b.(*StorageClasses), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*onmetal.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_onmetal_WorkerStatus(a.(*WorkerStatus), b.(*onmetal.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*onmetal.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_onmetal_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*onmetal.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CloudControllerManagerConfig_To_onmetal_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *onmetal.CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_v1alpha1_CloudControllerManagerConfig_To_onmetal_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudControllerManagerConfig_To_onmetal_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *onmetal.CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudControllerManagerConfig_To_onmetal_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_onmetal_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *onmetal.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_onmetal_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_onmetal_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *onmetal.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_onmetal_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileConfig_To_onmetal_CloudProfileConfig(in *CloudProfileConfig, out *onmetal.CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]onmetal.MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.RegionConfigs = *(*[]onmetal.RegionConfig)(unsafe.Pointer(&in.RegionConfigs))
	if err := Convert_v1alpha1_StorageClasses_To_onmetal_StorageClasses(&in.StorageClasses, &out.StorageClasses, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_onmetal_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_onmetal_CloudProfileConfig(in *CloudProfileConfig, out *onmetal.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_onmetal_CloudProfileConfig(in, out, s)
}

func autoConvert_onmetal_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *onmetal.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.RegionConfigs = *(*[]RegionConfig)(unsafe.Pointer(&in.RegionConfigs))
	if err := Convert_onmetal_StorageClasses_To_v1alpha1_StorageClasses(&in.StorageClasses, &out.StorageClasses, s); err != nil {
		return err
	}
	return nil
}

// Convert_onmetal_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_onmetal_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *onmetal.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_onmetal_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_onmetal_ControlPlaneConfig(in *ControlPlaneConfig, out *onmetal.ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*onmetal.CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_onmetal_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_onmetal_ControlPlaneConfig(in *ControlPlaneConfig, out *onmetal.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_onmetal_ControlPlaneConfig(in, out, s)
}

func autoConvert_onmetal_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *onmetal.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_onmetal_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_onmetal_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *onmetal.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_onmetal_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_onmetal_InfrastructureConfig(in *InfrastructureConfig, out *onmetal.InfrastructureConfig, s conversion.Scope) error {
	out.NetworkRef = (*v1.LocalObjectReference)(unsafe.Pointer(in.NetworkRef))
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_onmetal_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_onmetal_InfrastructureConfig(in *InfrastructureConfig, out *onmetal.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_onmetal_InfrastructureConfig(in, out, s)
}

func autoConvert_onmetal_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *onmetal.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	out.NetworkRef = (*v1.LocalObjectReference)(unsafe.Pointer(in.NetworkRef))
	return nil
}

// Convert_onmetal_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_onmetal_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *onmetal.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_onmetal_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_onmetal_InfrastructureStatus(in *InfrastructureStatus, out *onmetal.InfrastructureStatus, s conversion.Scope) error {
	out.NetworkRef = in.NetworkRef
	out.NATGatewayRef = in.NATGatewayRef
	out.PrefixRef = in.PrefixRef
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_onmetal_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_onmetal_InfrastructureStatus(in *InfrastructureStatus, out *onmetal.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_onmetal_InfrastructureStatus(in, out, s)
}

func autoConvert_onmetal_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *onmetal.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	out.NetworkRef = in.NetworkRef
	out.NATGatewayRef = in.NATGatewayRef
	out.PrefixRef = in.PrefixRef
	return nil
}

// Convert_onmetal_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_onmetal_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *onmetal.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_onmetal_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_onmetal_MachineImage(in *MachineImage, out *onmetal.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Image = in.Image
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_v1alpha1_MachineImage_To_onmetal_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_onmetal_MachineImage(in *MachineImage, out *onmetal.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_onmetal_MachineImage(in, out, s)
}

func autoConvert_onmetal_MachineImage_To_v1alpha1_MachineImage(in *onmetal.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Image = in.Image
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_onmetal_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_onmetal_MachineImage_To_v1alpha1_MachineImage(in *onmetal.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_onmetal_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_onmetal_MachineImageVersion(in *MachineImageVersion, out *onmetal.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Image = in.Image
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_onmetal_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_onmetal_MachineImageVersion(in *MachineImageVersion, out *onmetal.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_onmetal_MachineImageVersion(in, out, s)
}

func autoConvert_onmetal_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *onmetal.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Image = in.Image
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_onmetal_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_onmetal_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *onmetal.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_onmetal_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_onmetal_MachineImages(in *MachineImages, out *onmetal.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]onmetal.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_onmetal_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_onmetal_MachineImages(in *MachineImages, out *onmetal.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_onmetal_MachineImages(in, out, s)
}

func autoConvert_onmetal_MachineImages_To_v1alpha1_MachineImages(in *onmetal.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_onmetal_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_onmetal_MachineImages_To_v1alpha1_MachineImages(in *onmetal.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_onmetal_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_RegionConfig_To_onmetal_RegionConfig(in *RegionConfig, out *onmetal.RegionConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Server = in.Server
	out.CertificateAuthorityData = *(*[]byte)(unsafe.Pointer(&in.CertificateAuthorityData))
	return nil
}

// Convert_v1alpha1_RegionConfig_To_onmetal_RegionConfig is an autogenerated conversion function.
func Convert_v1alpha1_RegionConfig_To_onmetal_RegionConfig(in *RegionConfig, out *onmetal.RegionConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegionConfig_To_onmetal_RegionConfig(in, out, s)
}

func autoConvert_onmetal_RegionConfig_To_v1alpha1_RegionConfig(in *onmetal.RegionConfig, out *RegionConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Server = in.Server
	out.CertificateAuthorityData = *(*[]byte)(unsafe.Pointer(&in.CertificateAuthorityData))
	return nil
}

// Convert_onmetal_RegionConfig_To_v1alpha1_RegionConfig is an autogenerated conversion function.
func Convert_onmetal_RegionConfig_To_v1alpha1_RegionConfig(in *onmetal.RegionConfig, out *RegionConfig, s conversion.Scope) error {
	return autoConvert_onmetal_RegionConfig_To_v1alpha1_RegionConfig(in, out, s)
}

func autoConvert_v1alpha1_StorageClass_To_onmetal_StorageClass(in *StorageClass, out *onmetal.StorageClass, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = in.Type
	return nil
}

// Convert_v1alpha1_StorageClass_To_onmetal_StorageClass is an autogenerated conversion function.
func Convert_v1alpha1_StorageClass_To_onmetal_StorageClass(in *StorageClass, out *onmetal.StorageClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_StorageClass_To_onmetal_StorageClass(in, out, s)
}

func autoConvert_onmetal_StorageClass_To_v1alpha1_StorageClass(in *onmetal.StorageClass, out *StorageClass, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = in.Type
	return nil
}

// Convert_onmetal_StorageClass_To_v1alpha1_StorageClass is an autogenerated conversion function.
func Convert_onmetal_StorageClass_To_v1alpha1_StorageClass(in *onmetal.StorageClass, out *StorageClass, s conversion.Scope) error {
	return autoConvert_onmetal_StorageClass_To_v1alpha1_StorageClass(in, out, s)
}

func autoConvert_v1alpha1_StorageClasses_To_onmetal_StorageClasses(in *StorageClasses, out *onmetal.StorageClasses, s conversion.Scope) error {
	if err := Convert_v1alpha1_StorageClass_To_onmetal_StorageClass(&in.DefaultStorageClass, &out.DefaultStorageClass, s); err != nil {
		return err
	}
	out.AdditionalStorageClasses = *(*[]onmetal.StorageClass)(unsafe.Pointer(&in.AdditionalStorageClasses))
	return nil
}

// Convert_v1alpha1_StorageClasses_To_onmetal_StorageClasses is an autogenerated conversion function.
func Convert_v1alpha1_StorageClasses_To_onmetal_StorageClasses(in *StorageClasses, out *onmetal.StorageClasses, s conversion.Scope) error {
	return autoConvert_v1alpha1_StorageClasses_To_onmetal_StorageClasses(in, out, s)
}

func autoConvert_onmetal_StorageClasses_To_v1alpha1_StorageClasses(in *onmetal.StorageClasses, out *StorageClasses, s conversion.Scope) error {
	if err := Convert_onmetal_StorageClass_To_v1alpha1_StorageClass(&in.DefaultStorageClass, &out.DefaultStorageClass, s); err != nil {
		return err
	}
	out.AdditionalStorageClasses = *(*[]StorageClass)(unsafe.Pointer(&in.AdditionalStorageClasses))
	return nil
}

// Convert_onmetal_StorageClasses_To_v1alpha1_StorageClasses is an autogenerated conversion function.
func Convert_onmetal_StorageClasses_To_v1alpha1_StorageClasses(in *onmetal.StorageClasses, out *StorageClasses, s conversion.Scope) error {
	return autoConvert_onmetal_StorageClasses_To_v1alpha1_StorageClasses(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_onmetal_WorkerStatus(in *WorkerStatus, out *onmetal.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]onmetal.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_onmetal_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_onmetal_WorkerStatus(in *WorkerStatus, out *onmetal.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_onmetal_WorkerStatus(in, out, s)
}

func autoConvert_onmetal_WorkerStatus_To_v1alpha1_WorkerStatus(in *onmetal.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_onmetal_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_onmetal_WorkerStatus_To_v1alpha1_WorkerStatus(in *onmetal.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_onmetal_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}
