---
apiVersion: v1
kind: Secret
metadata:
  name: backupprovider
  namespace: shoot--foobar--ironcore
type: Opaque
data:
# namespace: base64(namespace)
# kubeconfig: base64(kubecconfig)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: BackupEntry
metadata:
  name: shoot--foobar--ironcore--sd34f
spec:
  type: ironcore
  region: europe-central
  bucketName: cloud--ironcore--fg2d6
  secretRef:
    name: backupprovider
    namespace: garden