---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--onmetal
---
apiVersion: v1
kind: Secret
metadata:
  name: core-onmetal
  namespace: shoot--foobar--onmetal
type: Opaque
data:
# serviceaccount.json: base64(serviceaccount-json)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--onmetal
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Shoot
    spec:
      networking:
        pods: 10.243.128.0/17
        services: 10.243.0.0/17
    status:
      lastOperation:
        state: Succeeded

---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Infrastructure
metadata:
  name: onmetal-infra
  namespace: shoot--foobar--onmetal
spec:
  type: onmetal
  region: europe-west1
  secretRef:
    namespace: shoot--foobar--onmetal
    name: core-onmetal
  providerConfig:
    apiVersion: onmetal.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    networks:
      # networkName: my-network
