apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.service.topologyAwareRouting.enabled }}
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
  {{- end }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
{{ include "labels" . | indent 4 }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.global.webhookConfig.serverPort }}
