apiVersion: v1
kind: Secret
metadata:
  name: cloud-provider-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  namespace: {{ .Values.namespace | b64enc }}
  kubeconfig: {{ .Values.kubeconfig | b64enc }}