{{- range $key, $value := .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $value.name }}
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
    {{- if $value.default }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- else }}
    storageclass.kubernetes.io/is-default-class: "false"
    {{- end }}
parameters:
  type: {{ $value.type }}
{{- if $value.expandable }}
allowVolumeExpansion: true
{{- else }}
allowVolumeExpansion: false
{{- end }}
provisioner: csi.onmetal.de
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end }}