{{- range $key, $value := .Values.volumeClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $value.storageClassName }}
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
    {{- if $value.default }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- else }}
    storageclass.kubernetes.io/is-default-class: "false"
    {{- end }}
parameters:
  type: {{ $value.name }}
allowVolumeExpansion: true
provisioner: onmetal-csi-driver
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end }}
