regions:
  - name: foo
    kubeConfigStub: |
      bar

image:
  repository: ghcr.io/onmetal/gardener-extension-provider-onmetal
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
maxUnavailable: 1
maxSurge: 50%

resources: {}
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 50m
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"

metricsPort: 8080
healthPort: 8081

controllers:
  controlplane:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  heartbeat:
    renewIntervalSeconds: 30
  infrastructure:
    concurrentSyncs: 5
  worker:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

disableControllers: []
disableWebhooks: []
ignoreResources: false

webhookConfig:
  servicePort: 443
  serverPort: 10250

leaderElection:
  resourceLock: leases

## settings for metrics, e.g. scraping by seed-prometheus
##
metrics:
  ## enable metrics scraping
  ##
  enableScraping: true

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  etcd:
    storage:
      className: gardener.cloud-fast
      capacity: 25Gi
      provisioner: kubernetes.io/gce-pd
      volumeBindingMode: WaitForFirstConsumer
  featureGates: {}
#   DisableGardenerServiceAccountCreation: false
gardener:
  version: ""
  seed:
    provider: onmetal
