image:
  repository: ghcr.io/onmetal/gardener-extension-provider-onmetal
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
maxUnavailable: 1
maxSurge: 50%

resources: {}
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 50m
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"

metricsPort: 8080
healthPort: 8081

controllers:
  backupbucket:
    concurrentSyncs: 5
  backupentry:
    concurrentSyncs: 5
  controlplane:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  heartbeat:
    renewIntervalSeconds: 30
  infrastructure:
    concurrentSyncs: 5
  bastion:
    concurrentSyncs: 5
  worker:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

disableControllers: []
disableWebhooks: []
ignoreResources: false

# Overwrite component images if needed e.g. in dev/testing environments
#imageVectorOverwrite: |
#  images:
#    - name: cloud-controller-manager
#      sourceRepository: github.com/onmetal/cloud-provider-onmetal
#      repository: ghcr.io/onmetal/cloud-provider-onmetal
#      tag: "sha-889754f"
#    - name: machine-controller-manager-provider-onmetal
#      sourceRepository: github.com/onmetal/machine-controller-manager-provider-onmetal
#      repository: ghcr.io/onmetal/machine-controller-manager-provider-onmetal
#      tag: "sha-361a2de"
#    - name: csi-driver
#      sourceRepository: github.com/onmetal/onmetal-csi-driver
#      repository: ghcr.io/onmetal/onmetal-csi-driver
#      tag: "v0.1.3"

webhookConfig:
  servicePort: 443
  serverPort: 10250

## settings for metrics, e.g. scraping by seed-prometheus
##
metrics:
  ## enable metrics scraping
  ##
  enableScraping: true

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  etcd:
    storage:
      className: gardener.cloud-fast
      capacity: 25Gi
      provisioner: kubernetes.io/gce-pd
      volumeBindingMode: WaitForFirstConsumer
  featureGates: {}
  bastionConfig:
    image: ""
    machineClassName: ""
    volumeClassName: ""
  backupBucketConfig:
    bucketClassName: ""
#   DisableGardenerServiceAccountCreation: false
gardener:
  version: ""
  gardenlet:
    featureGates: {}
  seed:
    provider: onmetal
