images:
  csi-driver: image-repository:image-tag
  csi-node-driver-registrar: image-repository:image-tag
  csi-liveness-probe: image-repository:image-tag

socketPath: /csi/csi.sock
vpaEnabled: false

resources:
  driver:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      memory: 400Mi
  nodeDriverRegistrar:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 50Mi
  livenessProbe:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 300Mi

vpa:
  resourcePolicy:
    driver:
      maxAllowed:
        cpu: 2
        memory: 4G
    nodeDriverRegistrar:
      maxAllowed:
        cpu: 1
        memory: 3G
    livenessProbe:
      maxAllowed:
        cpu: 1
        memory: 3G
